In [6]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

from data_loader import load_options_data

DATA_PATH = PROJECT_ROOT / "data" / "raw" / "spy_options_sample.csv"

df = load_options_data(DATA_PATH)
df.head()

,quote_date,expiration,strike,option_type,bid,ask,last,volume,open_interest,underlying_price,risk_free_rate,mid_price,bid_ask_spread,time_to_expiration,moneyness
0,2026-01-15,2026-02-20,580,C,24.8,25.2,25.00,1200,18500,600.0,0.045,25.00,0.4,0.09863,0.966667
1,2026-01-15,2026-02-20,590,C,16.9,17.3,17.10,1500,21000,600.0,0.045,17.10,0.4,0.09863,0.983333
2,2026-01-15,2026-02-20,600,C,10.4,10.8,10.60,2400,33000,600.0,0.045,10.60,0.4,0.09863,1.000000
3,2026-01-15,2026-02-20,610,C,6.0,6.3,6.15,1800,27000,600.0,0.045,6.15,0.3,0.09863,1.016667
4,2026-01-15,2026-02-20,620,C,3.3,3.6,3.45,1000,19000,600.0,0.045,3.45,0.3,0.09863,1.033333

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df[[
    "quote_date",
    "expiration",
    "strike",
    "option_type",
    "bid",
    "ask",
    "mid_price",
    "bid_ask_spread",
    "time_to_expiration",
    "moneyness"
]]

In [ ]:
""" test """
from black_scholes import black_scholes_price

df["bs_price_20vol"] = black_scholes_price(
    S=df["underlying_price"],
    K=df["strike"],
    T=df["time_to_expiration"],
    r=df["risk_free_rate"],
    sigma=0.20,
    option_type=df["option_type"],
    q=0.0,
)

df[[
    "strike",
    "option_type",
    "mid_price",
    "bs_price_20vol",
    "moneyness",
    "time_to_expiration"
]]

,strike,option_type,mid_price,bs_price_20vol,moneyness,time_to_expiration
0,580,C,25.00,28.698088,0.966667,0.09863
1,590,C,17.10,22.023235,0.983333,0.09863
2,600,C,10.60,16.364965,1.000000,0.09863
3,610,C,6.15,11.753653,1.016667,0.09863
4,620,C,3.45,8.148160,1.033333,0.09863
5,580,P,4.75,6.129546,0.966667,0.09863
6,590,P,7.40,9.410407,0.983333,0.09863
7,600,P,10.30,13.707853,1.000000,0.09863
8,610,P,14.90,19.052255,1.016667,0.09863
9,620,P,20.50,25.402476,1.033333,0.09863

In [ ]:
""" test """
from implied_vol import implied_volatility

iv = implied_volatility(
    market_price=14.833592055,
    S=600,
    K=600,
    T=30/365,
    r=0.045,
    option_type="C",
    q=0.0,
)

iv

0.19999999954372455

In [ ]:
df["implied_vol"] = df.apply(
    lambda row: implied_volatility(
        market_price=row["mid_price"],
        S=row["underlying_price"],
        K=row["strike"],
        T=row["time_to_expiration"],
        r=row["risk_free_rate"],
        option_type=row["option_type"],
        q=0.0,
    ),
    axis=1,
)

df[[
    "strike",
    "option_type",
    "mid_price",
    "bs_price_20vol",
    "implied_vol",
    "moneyness",
    "time_to_expiration"
]]