In [12]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

from data_loader import load_options_data

DATA_PATH = PROJECT_ROOT / "data" / "raw" / "spy_options_sample.csv"

df = load_options_data(DATA_PATH)
df.head()

,quote_date,expiration,strike,option_type,bid,ask,last,volume,open_interest,underlying_price,risk_free_rate,mid_price,bid_ask_spread,time_to_expiration,moneyness
0,2026-01-15,2026-02-20,580,C,24.8,25.2,25.00,1200,18500,600.0,0.045,25.00,0.4,0.098630,0.966667
1,2026-01-15,2026-02-20,590,C,16.9,17.3,17.10,1500,21000,600.0,0.045,17.10,0.4,0.098630,0.983333
2,2026-01-15,2026-03-20,600,C,10.4,10.8,10.60,2400,33000,600.0,0.045,10.60,0.4,0.175342,1.000000
3,2026-01-15,2026-04-20,610,C,6.0,6.3,6.15,1800,27000,600.0,0.045,6.15,0.3,0.260274,1.016667
4,2026-01-15,2026-04-20,620,C,3.3,3.6,3.45,1000,19000,600.0,0.045,3.45,0.3,0.260274,1.033333

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   quote_date          10 non-null     datetime64[ns]
 1   expiration          10 non-null     datetime64[ns]
 2   strike              10 non-null     int64
 3   option_type         10 non-null     object
 4   bid                 10 non-null     float64
 5   ask                 10 non-null     float64
 6   last                10 non-null     float64
 7   volume              10 non-null     int64
 8   open_interest       10 non-null     int64
 9   underlying_price    10 non-null     float64
 10  risk_free_rate      10 non-null     float64
 11  mid_price           10 non-null     float64
 12  bid_ask_spread      10 non-null     float64
 13  time_to_expiration  10 non-null     float64
 14  moneyness           10 non-null     float64
dtypes: datetime64[ns](2), float64(9), int64(3), object(1)
memory usage: 1.3+ KB

In [14]:
df.describe()

,quote_date,expiration,strike,bid,ask,last,volume,open_interest,underlying_price,risk_free_rate,mid_price,bid_ask_spread,time_to_expiration,moneyness
count,10,10,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000,10.000000,10.00000,10.000000,10.000000
mean,2026-01-15 00:00:00,2026-04-26 09:36:00,600.00000,11.820000,12.210000,12.015000,1600.000000,24450.000000,600.0,0.045,12.015000,0.39000,0.277808,1.000000
min,2026-01-15 00:00:00,2026-02-20 00:00:00,580.00000,3.300000,3.600000,3.450000,900.000000,18000.000000,600.0,0.045,3.450000,0.30000,0.098630,0.966667
25%,2026-01-15 00:00:00,2026-03-27 18:00:00,590.00000,6.300000,6.625000,6.462500,1225.000000,19500.000000,600.0,0.045,6.462500,0.32500,0.196575,0.983333
50%,2026-01-15 00:00:00,2026-04-20 00:00:00,600.00000,10.250000,10.650000,10.450000,1550.000000,23500.000000,600.0,0.045,10.450000,0.40000,0.260274,1.000000
75%,2026-01-15 00:00:00,2026-06-12 06:00:00,610.00000,16.350000,16.750000,16.550000,1775.000000,26750.000000,600.0,0.045,16.550000,0.40000,0.406164,1.016667
max,2026-01-15 00:00:00,2026-06-20 00:00:00,620.00000,24.800000,25.200000,25.000000,2600.000000,35000.000000,600.0,0.045,25.000000,0.60000,0.427397,1.033333
std,NaN,NaN,14.90712,7.131433,7.191422,7.161357,557.773351,5946.287357,0.0,0.000,7.161357,0.08756,0.127777,0.024845

In [15]:
df[[
    "quote_date",
    "expiration",
    "strike",
    "option_type",
    "bid",
    "ask",
    "mid_price",
    "bid_ask_spread",
    "time_to_expiration",
    "moneyness"
]]

,quote_date,expiration,strike,option_type,bid,ask,mid_price,bid_ask_spread,time_to_expiration,moneyness
0,2026-01-15,2026-02-20,580,C,24.8,25.2,25.00,0.4,0.098630,0.966667
1,2026-01-15,2026-02-20,590,C,16.9,17.3,17.10,0.4,0.098630,0.983333
2,2026-01-15,2026-03-20,600,C,10.4,10.8,10.60,0.4,0.175342,1.000000
3,2026-01-15,2026-04-20,610,C,6.0,6.3,6.15,0.3,0.260274,1.016667
4,2026-01-15,2026-04-20,620,C,3.3,3.6,3.45,0.3,0.260274,1.033333
5,2026-01-15,2026-04-20,580,P,4.6,4.9,4.75,0.3,0.260274,0.966667
6,2026-01-15,2026-05-20,590,P,7.2,7.6,7.40,0.4,0.342466,0.983333
7,2026-01-15,2026-06-20,600,P,10.1,10.5,10.30,0.4,0.427397,1.000000
8,2026-01-15,2026-06-20,610,P,14.7,15.1,14.90,0.4,0.427397,1.016667
9,2026-01-15,2026-06-20,620,P,20.2,20.8,20.50,0.6,0.427397,1.033333

In [16]:
""" test """
from black_scholes import black_scholes_price

df["bs_price_20vol"] = black_scholes_price(
    S=df["underlying_price"],
    K=df["strike"],
    T=df["time_to_expiration"],
    r=df["risk_free_rate"],
    sigma=0.20,
    option_type=df["option_type"],
    q=0.0,
)

df[[
    "strike",
    "option_type",
    "mid_price",
    "bs_price_20vol",
    "moneyness",
    "time_to_expiration"
]]

,strike,option_type,mid_price,bs_price_20vol,moneyness,time_to_expiration
0,580,C,25.00,28.698088,0.966667,0.098630
1,590,C,17.10,22.023235,0.983333,0.098630
2,600,C,10.60,22.408009,1.000000,0.175342
3,610,C,6.15,23.050445,1.016667,0.260274
4,620,C,3.45,18.806576,1.033333,0.260274
5,580,P,4.75,12.835383,0.966667,0.260274
6,590,P,7.40,19.080546,0.983333,0.342466
7,600,P,10.30,25.596464,1.000000,0.427397
8,610,P,14.90,30.429512,1.016667,0.427397
9,620,P,20.50,35.752125,1.033333,0.427397

In [17]:
""" test """
from implied_vol import implied_volatility

iv = implied_volatility(
    market_price=14.833592055,
    S=600,
    K=600,
    T=30/365,
    r=0.045,
    option_type="C",
    q=0.0,
)

iv

0.19999999954372455

In [18]:
df["implied_vol"] = df.apply(
    lambda row: implied_volatility(
        market_price=row["mid_price"],
        S=row["underlying_price"],
        K=row["strike"],
        T=row["time_to_expiration"],
        r=row["risk_free_rate"],
        option_type=row["option_type"],
        q=0.0,
    ),
    axis=1,
)

df[[
    "strike",
    "option_type",
    "mid_price",
    "bs_price_20vol",
    "implied_vol",
    "moneyness",
    "time_to_expiration"
]]

,strike,option_type,mid_price,bs_price_20vol,implied_vol,moneyness,time_to_expiration
0,580,C,25.00,28.698088,0.133877,0.966667,0.098630
1,590,C,17.10,22.023235,0.127595,0.983333,0.098630
2,600,C,10.60,22.408009,0.080361,1.000000,0.175342
3,610,C,6.15,23.050445,0.061351,1.016667,0.260274
4,620,C,3.45,18.806576,0.067469,1.033333,0.260274
5,580,P,4.75,12.835383,0.120018,0.966667,0.260274
6,590,P,7.40,19.080546,0.109096,0.983333,0.342466
7,600,P,10.30,25.596464,0.099004,1.000000,0.427397
8,610,P,14.90,30.429512,0.100461,1.016667,0.427397
9,620,P,20.50,35.752125,0.102044,1.033333,0.427397

In [19]:
""" test """
from greeks import delta, gamma, vega, theta

df["delta"] = delta(
    S=df["underlying_price"],
    K=df["strike"],
    T=df["time_to_expiration"],
    r=df["risk_free_rate"],
    sigma=df["implied_vol"],
    option_type=df["option_type"],
    q=0.0,
)

df["gamma"] = gamma(
    S=df["underlying_price"],
    K=df["strike"],
    T=df["time_to_expiration"],
    r=df["risk_free_rate"],
    sigma=df["implied_vol"],
    q=0.0,
)

df["vega"] = vega(
    S=df["underlying_price"],
    K=df["strike"],
    T=df["time_to_expiration"],
    r=df["risk_free_rate"],
    sigma=df["implied_vol"],
    q=0.0,
)

df["theta"] = theta(
    S=df["underlying_price"],
    K=df["strike"],
    T=df["time_to_expiration"],
    r=df["risk_free_rate"],
    sigma=df["implied_vol"],
    option_type=df["option_type"],
    q=0.0,
)

df[[
    "strike",
    "option_type",
    "mid_price",
    "implied_vol",
    "delta",
    "gamma",
    "vega",
    "theta"
]]

,strike,option_type,mid_price,implied_vol,delta,gamma,vega,theta
0,580,C,25.00,0.133877,0.824566,0.010234,0.486497,-0.148373
1,590,C,17.10,0.127595,0.708916,0.014262,0.646140,-0.164838
2,600,C,10.60,0.080361,0.599212,0.019145,0.971160,-0.103990
3,610,C,6.15,0.061351,0.445022,0.021041,1.209557,-0.071218
4,620,C,3.45,0.067469,0.275876,0.016182,1.022977,-0.056308
5,580,P,4.75,0.120018,-0.219000,0.008039,0.903980,-0.040317
6,590,P,7.40,0.109096,-0.295785,0.009018,1.212979,-0.030140
7,600,P,10.30,0.099004,-0.370884,0.009730,1.482176,-0.018327
8,610,P,14.90,0.100461,-0.470504,0.010096,1.560587,-0.013608
9,620,P,20.50,0.102044,-0.567440,0.009824,1.542453,-0.005946